config/routes.rb
Rails.application.routes.draw do
  resources :users

  root 'users#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :month, :day, :year
  validate :validate_birthday

  validates :emp_id, :name, :birthday, :phone1, :post_number, :address, presence: true
  validates :emp_id, uniqueness: true

private
  def convert_birthday
    begin
      self.birthday = Date.new(self.year.to_i, self.month.to_i, self.day.to_i)
    rescue ArgumentError
      false
    end
  end

  def validate_birthday
    errors.add("Created at date", "is invalid.") unless convert_birthday
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.create(user_params)
    @users = User.all
    # respond_to do |format|
    #   if @user.save
    #     format.html { redirect_to @user, notice: '社員データの登録を行いました。' }
    #     format.json { render :show, status: :created, location: @user }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @user.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if @user.update(user_params)
      @users = User.all
    else
      render 'error_notice'
    end

    # respond_to do |format|
    #   if @user.update(user_params)
    #     format.html { redirect_to @user, notice: '社員データの更新を行いました。' }
    #     format.json { render :show, status: :ok, location: @user }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @user.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    redirect_to users_url
    # respond_to do |format|
    #   format.html { redirect_to users_url, notice: '社員データの削除を行いました。' }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:emp_id, :name, :birthday, :phone1, :phone2, :post_number, :address, :other, :year, :month, :day )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Master Employee Table</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_edit.html.erb
<%= render partial: 'modal' %>

app/views/users/_index.html.erb
<% @users.each do |user| %>
  <tr>
    <td><%= user.emp_id %></td>
    <td><%= user.name %></td>
    <td><%= (Date.today.strftime("%Y%m%d").to_i - user.birthday.strftime("%Y%m%d").to_i) / 10000 %>歳</td>
    <td><%= user.phone1 %></td>
    <td><%= user.phone2 %></td>
    <td><%= user.post_number %></td>
    <td><%= user.address %></td>
    <td><%= user.other %></td>
    <td><%= link_to 'Show', user_path(user), remote: true %></td>
    <td><%= link_to 'Edit', edit_user_path(user), remote: true %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'この社員データを削除してもよろしいでしょうか？' } %></td>
  </tr>
<% end %>

app/views/users/_modal.html.erb
<div class="modal-dialog">
  <div class="modal-content">

    <%= form_for(@user, remote: true) do |f| %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">社員データ登録</h4>
          <!-- エラーログを表示する。 -->
          <div class="error-notice"></div>
      </div>
      <div class="modal-body">

      <div class="field">
        <%= f.label "社員番号" %><br>
        <%= f.text_field :emp_id %>
      </div>

      <div class="field">
        <%= f.label "社員名称" %><br>
        <%= f.text_field :name %>
      </div>

      <div class="field">
        <%= f.label "生年月日" %><br>
        <%= f.select :year, ((Time.now.year - 20)..Time.now.year).to_a, selected: @user.birthday.year %>
        <%= f.select :month, (1..12).to_a, selected: @user.birthday.month %>
        <%= f.select :day, (1..31).to_a, selected: @user.birthday.day %>
      </div>

      <div class="field">
        <%= f.label "電話番号1" %><br>
        <%= f.text_field :phone1 %>
      </div>

      <div class="field">
        <%= f.label "電話番号2" %><br>
        <%= f.text_field :phone2 %>
      </div>

      <div class="field">
        <%= f.label "郵便番号" %><br>
        <%= f.text_field :post_number %>
      </div>

      <div class="field">
        <%= f.label "住所" %><br>
        <%= f.text_field :address %>
      </div>

      <div class="field">
        <%= f.label "備考欄" %><br>
        <%= f.text_area :other %>
      </div>
      
      </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.submit "Save", :class => "btn btn-primary" %>
        </div>
      </div>
      
    <% end %>

  </div>
</div>

app/views/users/_new.html.erb
<%= render partial: 'modal' %>

app/views/users/_save.js.erb
$(".user-index").html("<%= escape_javascript(render 'index') %>")
$("#user-modal").modal("hide")

app/views/users/create.js.erb
<%= render 'save' %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/edit.js.erb
// $("#user-modal").modal("hide")
$("#user-modal").html("<%= escape_javascript(render 'edit') %>")
$("#user-modal").modal("show")

app/views/users/error_notice.js.erb
$(".error-notice").append("<p>変更された値に不正があります。<p>")

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-10">
    <h1>Employees Master Table</h1>
  </div>
  <div class="col-md-2" >
    <%= link_to '社員データ新規作成', new_user_path, remote: true %>
  </div>
</div>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>社員CD</th>
      <th>社員名称</th>
      <th>年齢</th>
      <th>電話番号1</th>
      <th>電話番号2</th>
      <th>郵便番号</th>
      <th>住所</th>
      <th>備考欄</th>
      <th colspan="3">編集フォーム</th>
    </tr>
  </thead>

  <tbody class="user-index">
    <%= render "index" %>
  </tbody>
</table>
<br>

<script type="text/javascript">
$(function(){
  $('.table tr').hover(
    function(){
      $(this).addClass('hv');
    },
    function(){
      $(this).removeClass('hv');
    }
  );
});
</script>

<div id="user-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <!-- jsの内容をここに出力する。 -->
</div>

app/views/users/new.js.erb
$("#user-modal").html("<%= escape_javascript(render 'new') %>")
$("#user-modal").modal("show")

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>社員番号</strong>
  <%= @user.emp_id %>
</p>

<p>
  <strong>社員名称</strong>
  <%= @user.name %>
</p>

<p>
  <strong>生年月日</strong>
  <%= @user.birthday %>
</p>

<p>
  <strong>電話番号1</strong>
  <%= @user.phone1 %>
</p>

<p>
  <strong>電話番号2</strong>
  <%= @user.phone2 %>
</p>

<p>
  <strong>郵便番号</strong>
  <%= @user.post_number %>
</p>

<p>
  <strong>住所</strong>
  <%= @user.address %>
</p>

<p>
  <strong>備考欄</strong>
  <%= @user.other %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/show.js.erb
$("#user-modal").html("<%= escape_javascript(render 'detail') %>")
$("#user-modal").modal("show")

app/views/users/update.js.erb
<%= render 'save' %>